### ISSUE TITLE
CI pipeline tests

### ISSUE THREAD

**Issue by paulfantom** [andrewrothstein/ansible-kafka#2]
Have you considered using [molecule](https://github.com/metacloud/molecule) for CI pipeline? This framework can use docker, testinfra (for tests), ansible-lint and it also tests for idempotence.
If you want I could try to implement it for this role (you can see how it works by looking at this repo: https://github.com/cloudalchemy/ansible-grafana)

**Comment by andrewrothstein** [comment]
never heard of it. looks awesome. my python duct-tape-and-dental-floss solution works quite well for me so I'll pass for now. thanks for bringing to my attention!
